version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    environment:
      PORT: 3000
      DB_DIALECT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password

  postgres:
    image: postgres:12-alpine
    container_name: backend-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend-task
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
